dist: xenial
language: python

# Existing Python versions
python:
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py -q install
  - pip install -r requirements_ci.txt

# run tests
script:
  - python -m pytest --cov=tidd

# report results
after_success:
  - coveralls